#ifndef _WINTERNALZ_H_
#define _WINTERNALZ_H_

#include <WinNT.h>

typedef struct _EXCEPTION_REGISTRATION_RECORD
{
	union
	{
		struct _EXCEPTION_REGISTRATION_RECORD *next;
		struct _EXCEPTION_REGISTRATION_RECORD *prev;
	};
	PEXCEPTION_ROUTINE	handler;
} EXCEPTION_REGISTRATION_RECORD, *PEXCEPTION_REGISTRATION_RECORD;

#endif
